# Single-stage dev setup
FROM node:18
WORKDIR /app

# install npm packages
COPY package.json package-lock.json .npmrc ./
RUN --mount=type=secret,id=GH_TOKEN GH_NPM_AUTH=$(cat /run/secrets/GH_TOKEN) npm ci

# run dev server
CMD [ "npm", "start" ]
