#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run full linting with type-aware rules on entire project
npm run lint

# Run TypeScript type-checking on entire project
npm run test:type-check

