on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      registry:
        type: string
        required: true
      registry-user:
        type: string
        required: true
      image-name:
        type: string
        required: true
      dockerfile-path:
        type: string
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-user }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: '{{defaultContext}}/${{ inputs.dockerfile-path }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.version }}
          secrets: |
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
