# Build and Push to GHCR

name: Create and publish Docker image to GHCR

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build_publish.yml
    with:
      version: latest
      registry: ghcr.io
      registry-user: ${{ github.actor }}
      image-name: nismod/irv-frontend
      dockerfile-path: containers/Dockerfile-prod
    secrets: inherit
    permissions:
      contents: read
      packages: write
