# Build and Push to GHCR

name: Create and publish Docker image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build_publish.yml
    with:
      version: '0.21'
      registry: ghcr.io
      registry-user: ${{ github.actor }}
      image-name: nismod/irv-frontend
      dockerfile-path: containers/Dockerfile-prod
    secrets: inherit
    permissions:
      contents: read
      packages: write
