# Build and Push to GHCR

name: Create and publish Docker image to GHCR

on:
  push:
    branches:
      - main

env:
  VERSION: 0.20
  REGISTRY: ghcr.io
  IMAGE_NAME: nismod/gri-web-server

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: '{{defaultContext}}/containers/Dockerfile-prod'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          secrets: |
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
